name: ci
on:
  push:
    branches:
      - main
      - master

jobs:
  build_css:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source Git branch
        uses: actions/checkout@v2

      - name: Install and Build
        run: |
          cd frontend/
          sudo npm install
          sudo npm install -g browserify
          npm run build-bundle-js
          npm run predeploy

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: .
