name: ci
on:
  push:
    branches:
      - main
      - master

jobs:
  build_css:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source Git branch
        uses: actions/checkout@v3

      - name: Install and Build
        run: |
          cd frontend/
          npm ci

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: frontend/
