name: ci
on:
  push:
    branches:
      - main
      - master

jobs:
  build_css:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source Git branch
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Compile CSS from SCSS files
        uses: gha-utilities/sass-build@v0.4.3
        with:
          source: scss
          destination: assets/css
